language: node_js

jobs:
  include:
    - stage: "Automated Tests"
      name: "Lint commit messages"
      script: commitlint-travis
    - name: "Lint code"
      script: yarn lint
    - stage: "Semantic Release"
      name: "Release"
      script: yarn release-all

notifications:
  email: false
